<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <style>
        body {
            margin: 0;
            padding: 0;
            min-height: 100vh; 
            display: flex;
            flex-direction: column;
            background-image: url('home.jpg');
            background-size: cover;
            background-position: center;;
        }
        .content {
            flex: 1;
            padding-bottom: 20px;
        }
        .footer-Container {
            text-align: center;
            background-color: rgba(255, 255, 255, 0.8);
            padding: 10px 0;
            width: 100%;
        }
    </style>
</head>
<body>

    <div class="content">
       


    
    </div>
        
    <div class="footer-Container">
        <p>2024 TripScript - All rights reserved.</p>
    </div>
    
</body>
</html>