<!DOCTYPE html>
<?php require_once 'templates/header.phtml'?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="login" method="$_POST">
        <label for="userName">Ingrese nombre de usuario</label>
        <input type="text" name="userName">
        <label for="password">Ingrese contraseña</label>
        <input type="text" name="">
</body>
</html>

<?php require_once 'templates/footer.phtml'?>