<?php require_once 'templates/header.phtml'?>
    <h1>Registrate</h1>
    <form action="userController.php" method="POST">
    <div class="mb-3">
        <label for="name">Ingrese nombre </label>
        <input type="text" name="name" require>
    </div>
    <div class="mb-3">
        <label for="lastName">Ingrese apellido</label>
        <input type="text" name="lastName"require>  
    </div>
    <div class="mb-3">
        <label for="dni">Ingrese dni</label>
        <input type="number" name="dni"require>
    </div>
    <div class="mb-3">
        <label for="email">Ingrese email</label>
        <input type="email" name="email"require>
    </div>
    <div class="mb-3">
        <label for="contraseña">Ingrese contraseña</label>
        <input type="text" name="email"require>
    </div>
    <div class="mb-3">
        <label for="preferences">Preferencias</label>
        <select name="preferences" require>
            <option value="warmWheater">Clima calido</option>
            <option value="coldWheather">Clima frio</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
    </form>

<?php require_once 'templates/footer.phtml'?>
