<form action="addDestination" method="get">
<div class="mb-3">
        <label for="name">Ingrese el nombre del destino</label>
        <input type="text" name="nme" >
    </div>
    <div class="mb-3">
        <label for="description">Ingrese descripcion</label>
        <input type="text" name="description" >
    </div>
    <div class="mb-3">
        <label for="attractions">Ingrese atraccionbes</label>
        <input type="text" name="attractions">
    </div>
    <div class="mb-3">
    <label for="season">Temporada alta</label>
        <select name="season" require>
            <option value="enero">Enero</option>
            <option value="febrero">Febrero</option>
            <option value="marzo">Marzo</option>
            <option value="abril">Abril</option>
            <option value="mayo">Mayo</option>
            <option value="junio">Junio</option>
            <option value="julio">Julio</option>
            <option value="agosto">Agosto</option>
            <option value="septiembre">Septiembre</option>
            <option value="octubre">Octubre</option>
            <option value="noviembre">Noviembre</option>
            <option value="diciembre">Diciembre</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Agregar destino</button>
</form>
</form>