<?php
require_once 'templates/header.phtml';
?>

<?php if ($error): ?>
    <div class='alert' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>

   
    <form action="login" method="POST" class="m-4">
        <h2>Iniciar sesión</h2>

        <div class="row mb-3">
            <div class="col-12">
                <label for="name">Ingrese nombre de usuario</label>
                <input type="text" name="name" id="name" required>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12">
                <label for="password">Ingrese contraseña</label>
                <input type="password" name="password" id="password" required>
            </div>
        </div>

        <button type="submit" class="btn btn-primary w-20">Iniciar Sesión</button>

        


    </form>
    

    
</body>
</html>


<?php
require_once 'templates/footer.phtml';
?>