<?php require_once 'templates/header.phtml'?>


<form action="<?= htmlspecialchars($ruta) ?>" method="POST" class="m-5">
    <h2>Realizá tu reserva</h2>
    
    <input type="hidden" name="bookingId" value="<?= htmlspecialchars($bookingId) ?>">
    <div class="mb-3">
        <label for="destination">Ingrese destino</label>
        <input type="text" name="destination" required>
    </div>
    <div class="mb-3">
        <label for="housing">Ingrese alojamiento</label>
        <input type="text" name="housing" required >
    </div>
    <div class="mb-3">
        <label for="checkin">Ingrese fecha de check-in</label>
        <input type="date" name="checkin" required>
    </div>
    <div class="mb-3">
        <label for="checkout">Ingrese fecha de check-out</label>
        <input type="date" name="checkout" required>
    </div>
    <button type="submit" class="btn btn-primary"><?= htmlspecialchars($button) ?></button>
</form>
<?php require_once 'templates/footer.phtml'?>