<?php require_once 'templates/header.phtml'?>
    <h1>Registrate</h1>
    <form action="register" method="POST">
    <div class="mb-3">
        <label for="name">Ingrese nombre </label>
        <input type="text" name="name" required>
    </div>
    <div class="mb-3">
        <label for="lastname">Ingrese apellido</label>
        <input type="text" name="lastname"required>  
    </div>
    <div class="mb-3">
        <label for="dni">Ingrese dni</label>
        <input type="number" name="dni"required>
    </div>
    <div class="mb-3">
        <label for="email">Ingrese email</label>
        <input type="email" name="email"required>
    </div>
    <div class="mb-3">
        <label for="password">Ingrese contraseña</label>
        <input type="password" name="password"required>
    </div>
    <div class="mb-3">
        <label for="preferences">Preferencias</label>
        <select name="preferences" required>
            <option value="clima calido">Clima calido</option>
            <option value="clima frio">Clima frio</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Registrarme</button>
    </form>

<?php require_once 'templates/footer.phtml'?>
