<?php require_once 'templates/header.phtml'?>

<div class="content">
<form action="addDestination" method="POST" class="m-4">
<h3>Añadí un nuevo destino</h3>

<form action="destinations" method="POST">
<div class="mb-3">
        <label for="name">Ingrese el nombre del destino</label>
        <input type="text" name="name" required>
    </div>
    <div class="mb-3">
        <label for="description">Ingrese descripción</label>
        <input type="text" name="description" required>
    </div>
    <div class="mb-3">
        <label for="attractions">Ingrese atracciones</label>
        <input type="text" name="attractions" required>
    </div>
    <div class="mb-3">
    <label for="season">Temporada alta</label>
        <select name="season" required>
            <option value="enero">Enero</option>
            <option value="febrero">Febrero</option>
            <option value="marzo">Marzo</option>
            <option value="abril">Abril</option>
            <option value="mayo">Mayo</option>
            <option value="junio">Junio</option>
            <option value="julio">Julio</option>
            <option value="agosto">Agosto</option>
            <option value="septiembre">Septiembre</option>
            <option value="octubre">Octubre</option>
            <option value="noviembre">Noviembre</option>
            <option value="diciembre">Diciembre</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Añadir destino</button>
</form>
</div>
</form>

<?php require_once 'templates/footer.phtml'?>