<?php require_once "templates/header.phtml"?>
<?php
session_start(); // asegurar que la sesión esté iniciada
$name = isset($_SESSION['name']) ? $_SESSION['name'] : 'Invitado'; // verifica si hay un nombre de usuario
?>

<div>
    <h2>Bienvenido a TripScript <?php echo htmlspecialchars($name) ?></h2>
</div>
<div>
    <h3>Reservas realizadas</h3>
</div>
<div class="session-actions">
    <a href="#">Cerrar sesión</a>
    <form action="user" method="POST" style="display:inline;">
        <input type="hidden" name="IDUSUARIO" value="<?php echo $_SESSION['IDUSUARIO']; ?>"> 
        <input type="hidden" name="action" value="deleteAccount">
        <button type="submit" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que deseas eliminar tu cuenta?');">Eliminar cuenta</button>
    </form>
</div>

<style>
    .session-actions {
        position: fixed;
        bottom: 60px;
        right: 20px;
        background-color: rgba(255, 255, 255, 0.9);
        padding: 10px;
        border-radius: 5px; 
    }

    .session-actions a {
        display: block; 
        margin-bottom: 5px; 
        color: #007bff; 
        text-decoration: none;
    }

    .session-actions a:hover {
        text-decoration: underline; /* subraya cuando pasa el mouse */
    }
</style>
<?php require_once "templates/footer.phtml"?>
